name: Создание релиза

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - run: npm ci
            - run: npm run test

    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - run: npm ci
            - run: npm run lint

    create-release-branch:
        needs: [test, eslint]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Create release branch
              run: |
                  git checkout -b releases/${{ github.run_number }}
                  git push origin releases/${{ github.run_number }}
